#!/bin/bash
set -e
set -o pipefail

# Input variables:
#
# - NXF_UUID: nextflow session id generated by tower
# - NXF_WORK: nextflow work directory
# - NXF_LOG_FILE: nextflow log file name
# - NXF_OUT_FILE: nextflow output file name
# - NXF_SCM_FILE: nextflow scm config file
# - NXF_IGNORE_RESUME_HISTORY: do not stop for missing nextflow history file
# - NXF_CONFIG_BASE64: nextflow config file encoded as base64 string
# - NXF_GLS_BASE64: google lifesciences creds encoded as base64 string
# - NXF_DEBUG: enable debugging mode
# - NXF_AWS_SSE_MODE: when provided, either `AES256` or `aws:kms`
# - NXF_AWS_SSE_KMS_KEY_ID: when provided the custom KMS key id
# - NXF_CLOUDCACHE_PATH: The object storage path where nextflow cache should be stored
# - TOWER_ACCESS_TOKEN: Tower access token
# - TOWER_WORKFLOW_ID: Workflow ID generated by Tower
# - TOWER_CONFIG_BASE64: tower config file encoded as base64 string
# - TOWER_CONFIG_FILE: tower config file name
# - TOWER_LAUNCH_UMASK: Sets umask before running NF. Useful to enable non-root containers to write to scratch folders.

[[ $NXF_DEBUG ]] && (env | sort) && set -x

function pre_run() {
    if [[ $NXF_PRERUN_BASE64 ]]; then
      ## https://stackoverflow.com/a/32596626/395921
      source /dev/stdin <<<"$(cat <(echo $NXF_PRERUN_BASE64 | base64 -d))" > >(tee -a $NXF_OUT_FILE) 2>&1
    fi
}

function post_run() {
    if [[ $NXF_POSTRUN_BASE64 ]]; then
      bash <(echo $NXF_POSTRUN_BASE64 | base64 -d) > >(tee -a $NXF_OUT_FILE) 2>&1 || true
    fi
}

function on_exit() {
    NXF_EXIT_STATUS=$?
    export NXF_EXIT_STATUS
    post_run
    save_cache
    exit $NXF_EXIT_STATUS
}

function save_cache() {
    nextflow -log .nextflow.cache.log -config-ignore-includes plugin nf-tower:cache-backup >> >(tee -a $NXF_OUT_FILE) 2>&1
}

function load_cache() {
    nextflow -config-ignore-includes plugin nf-tower:cache-restore > >(tee -a $NXF_OUT_FILE) 2>&1
}

function term_run() {
  kill -TERM $nf_pid
  wait $nf_pid
}

# save GLS creds and authenticate
if [[ $NXF_GLS_BASE64 ]]; then
  mkdir -p /.nextflow
  echo $NXF_GLS_BASE64 | base64 -d > /.nextflow/gls.json
  export GOOGLE_APPLICATION_CREDENTIALS=/.nextflow/gls.json
  gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}
  unset NXF_GLS_BASE64
fi

if [[ $TOWER_LAUNCH_UMASK ]]; then
  umask $TOWER_LAUNCH_UMASK
fi

## execute pre-run script
pre_run

## resolve the xpack license URL to the actual value
if [[ $NXF_XPACK_LICENSE == http://* || $NXF_XPACK_LICENSE == https://* ]]; then
export NXF_XPACK_LICENSE=$(curl -sL -H "user-agent: Nextflow/httpfs" --retry-connrefused --retry 5 $NXF_XPACK_LICENSE)
fi

# save nextflow config file
if [[ $NXF_CONFIG_BASE64 ]]; then
  echo $NXF_CONFIG_BASE64 | base64 -d > nextflow.config
  unset NXF_CONFIG_BASE64
fi

# save tower config file
if [[ $TOWER_CONFIG_BASE64 ]]; then
  echo $TOWER_CONFIG_BASE64 | base64 -d > $TOWER_CONFIG_FILE
fi

trap term_run TERM INT
trap on_exit EXIT

## restore the exec cache
load_cache

[[ $NXF_DEBUG ]] && nextflow -Dcapsule.log=verbose info -dd
NXF_JVM_ARGS=${NXF_JVM_ARGS:-'-XX:InitialRAMPercentage=40 -XX:MaxRAMPercentage=75'}
export NXF_JVM_ARGS

"$@" >> >(tee -a $NXF_OUT_FILE) 2>&1 &
nf_pid=$!
wait $nf_pid
