#cloud-config
package_upgrade: true
packages:
  - curl
  - wget
  - unzip
  - jq # Utilidad para parsear JSON

runcmd:
  - |
    iptables -P INPUT ACCEPT
    iptables -P FORWARD ACCEPT
    iptables -P OUTPUT ACCEPT
    iptables -t nat -F
    iptables -t mangle -F
    iptables -F
    iptables -X
    iptables-save > /etc/iptables/rules.v4


    wget -P /tmp https://github.com/juanfont/headscale/releases/download/v0.26.1/headscale_0.26.1_linux_amd64.deb
    apt install -y /tmp/headscale_0.26.1_linux_amd64.deb

    rm -rf /etc/headscale/config.yaml
    wget https://raw.githubusercontent.com/juanfont/headscale/refs/heads/main/config-example.yaml -O /etc/headscale/config.yaml

    sed -i "s/listen_addr: 127.0.0.1:8080/listen_addr: 0.0.0.0:443/g" /etc/headscale/config.yaml
    sed -i "s/server_url: http:\/\/127.0.0.1:8080/server_url: https:\/\/${domain_name}/g" /etc/headscale/config.yaml
    sed -i "s/acme_email: \"\"/acme_email: \"${email}\"/g" /etc/headscale/config.yaml
    sed -i "s/tls_letsencrypt_hostname: \"\"/tls_letsencrypt_hostname: \"${letsencrypt_hostname}\"/g" /etc/headscale/config.yaml

    systemctl enable headscale
    systemctl start headscale
    headscale user create nomad
    headscale user create cluster
