#cloud-config
package_upgrade: true
packages:
  - curl
  - wget
  - unzip
  - jq
  - docker-engine
  - nfs-utils

runcmd:
  # Instalar Docker
  - |
    # Add Docker's official GPG key:
    sudo apt-get update
    sudo apt-get install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    
    # Add the repository to Apt sources:
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$UBUNTU_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

  # Descargar y descomprimir Nomad
  - |
    wget -q https://releases.hashicorp.com/nomad/${nomad_version}/nomad_${nomad_version}_linux_amd64.zip
    unzip nomad_${nomad_version}_linux_amd64.zip
    sudo mv nomad /usr/local/bin/
    sudo chmod +x /usr/local/bin/nomad
    sudo mkdir -p /etc/nomad.d /opt/nomad/data    
    sudo chmod -R +r /etc/nomad.d/
    sudo chmod -R +r /opt/nomad/data

  # Obtener IP privada de la instancia (para auto-configuración)
  - |
    LOCAL_IP=$(hostname -I | awk '{print $1}')
    echo "Local IP: $LOCAL_IP"
    sed -i "s|__INSTANCE_PRIVATE_IP__|${first_nomad_server_hostname}|g" /etc/nomad.d/nomad.hcl

  - |
    echo "Reloading systemd daemon..."
    sudo systemctl daemon-reload
    sudo systemctl restart docker
    
    echo "Enabling and starting Nomad service..."
    sudo systemctl enable nomad.service
    sudo systemctl start nomad.service

write_files:
  # Configuración de Nomad Client
  - path: /etc/nomad.d/nomad.hcl
    permissions: "0640"
    owner: root:root
    content: |
      data_dir = "/opt/nomad/data"
      bind_addr = "0.0.0.0"
      client {
        enabled = true
        options {
          "driver.docker.enabled" = "true"
        }
      }
      plugin "docker" {
        config {
          allow_privileged = true
          volumes{
              enabled = true
          }
          gc {
            image = false
            image_delay = "1h"
          }
        }
      }

      consul {
        address = "__INSTANCE_PRIVATE_IP__:8500" # Se conecta a Consul local
      }

  # Systemd service para Nomad
  - path: /etc/systemd/system/nomad.service
    permissions: "0644"
    owner: root:root
    content: |
      [Unit]
      Description="HashiCorp Nomad"
      Documentation=https://www.nomadproject.io/
      Requires=network-online.target
      After=network-online.target consul.service
      [Service]
      ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      Restart=on-failure
      LimitNOFILE=65536
      [Install]
      WantedBy=multi-user.target

final_message: "Nomad client configured!"